image: openjdk:8-jdk

variables:
  GIT_DEPTH: "3"

cache:
  paths:
    - .apt-cache
    - .gradle/caches
    - .gradle/wrapper
    #- .android/build-cache

stages:
  - build
  #- execute

before_script:
  - export GRADLE_USER_HOME="$PWD/.gradle"
  - echo "$CI_PROJECT_DIR"
  - mkdir -p "$CI_PROJECT_DIR/.apt-cache/archives/partial"
  - apt-get update
  - apt-get -o dir::cache::archives="$CI_PROJECT_DIR/.apt-cache/archives" install -y zip

build:
  stage: build
  script: ./gradlew buildOtaOSS -s

after_script:
  - rm -f  $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
  - rm -fr $GRADLE_USER_HOME/caches/*/plugin-resolution/
