image: openjdk:8-jdk

stages:
  - build
  #- execute

before_script:
  - export GRADLE_USER_HOME="$PWD/.gradle"
  - apt-get update && apt-get install -y zip

build:
  stage: build
  script: ./gradlew buildOtaOSS -s

after_script:
  - rm -f  $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
  - rm -fr $GRADLE_USER_HOME/caches/*/plugin-resolution/

cache:
  paths:
    - .gradle/caches
    - .gradle/wrapper
    - .android/build-cache
